"""initial schema

Revision ID: f83bd3db5fa8
Revises: 
Create Date: 2026-08-09 00:46:45.987360
"""
from alembic import op
import sqlalchemy as sa


revision = 'f83bd3db5fa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vdo_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stored_file_id', sa.Integer(), nullable=False),
    sa.Column('hls_path', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vdo_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vdo_videos_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vdo_videos_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vdo_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vdo_videos_status'))
        batch_op.drop_index(batch_op.f('ix_vdo_videos_owner_id'))

    op.drop_table('vdo_videos')
    # ### end Alembic commands ###
